### ISSUE TITLE
closed connection, reason close, reconnecting in a few moments

### ISSUE THREAD

**Issue by Xnuvers007** [Nurutomo/wabot-aq#1096]
INFO [2022-07-21 09:33:23.646 +0000] (6044): validated connection successfully
    class: "Baileys"
INFO [2022-07-21 09:33:23.657 +0000] (6044): opened connection to WhatsApp Web
    class: "Baileys"
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:87:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:88:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:89:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:90:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:91:18)
    at WAConnection.emit (node:events:526:28)
    at WAConnection.emit (/bot/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection
INFO [2022-07-21 09:33:23.679 +0000] (6044): closed connection, reason close, reconnecting in a few seconds...
    class: "Baileys"
INFO [2022-07-21 09:33:28.075 +0000] (6044): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"

**Comment by RC047** [comment]
English:
Now WhatsApp is using the Multi-Device feature, so the old version of baileys will not support for the latest whatsapp version. Please use the latest version of baileys or use the old version of WhatsApp :)

Indonesian:
Sekarang WhatsApp menggunakan fitur Multi-Device,, jadi baileys versi lama tidak akan mendukung untuk versi whatsapp terbaru. Silahkan gunakan baileys versi terbaru atau gunakan WhatsApp versi lama :)
