### ISSUE TITLE
Ini Gimana?

### ISSUE THREAD

**Issue by fuadxtps23** [Nurutomo/wabot-aq#1103]
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at prepareSecretKey (node:internal/crypto/keys:584:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:141:10)
    at Object.aesEncrypt (C:\Users\Administrator\Downloads\wabot-aq-2.5.1\wabot-aq-2.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (C:\Users\Administrator\Downloads\wabot-aq-2.5.1\wabot-aq-2.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Users\Administrator\Downloads\wabot-aq-2.5.1\wabot-aq-2.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:513:28)
    at WAConnection.emit (C:\Users\Administrator\Downloads\wabot-aq-2.5.1\wabot-aq-2.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
} unhandledRejection

**Comment by fuadxtps23** [comment]
pas udah di scan gini
![image](https://user-images.githubusercontent.com/93533757/193464177-99207e72-f3e1-4aa6-8821-1f12267d3fdb.png)

**Comment by ubed354311** [comment]
wkwkwk sama saya
ini memang harus nunggu update an dari baileys nya

**Comment by fuadxtps23** [comment]
> wkwkwk sama kayak saya ini memang harus nunggu update an dari baileys nya

kapan ya diupdate
