### ISSUE TITLE
Sticker Error ga ada respon

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#136]
ERROR [2021-03-22 04:57:52.101 +0000] (1684): sticker1 is not defined
    ReferenceError: sticker1 is not defined
        at Object.<anonymous> (C:\Users\Administrator\Downloads\Compressed\wabot-aq-master\lib\sticker.js:102:3)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (C:\Users\Administrator\Downloads\Compressed\wabot-aq-master\plugins\sticker.js:2:21)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by RC047** [comment]
Baru update mah wajar pasti ada bug,, makanya klo ada update tunggu dulu sekitar 3-4 harian sabar :v

jangan lgsung maen apdet

**Comment by Ftwrr** [comment]
> Baru update mah wajar pasti ada bug,, makanya klo ada update tunggu dulu sekitar 3-4 harian sabar :v
> 
> jangan lgsung maen apdet

thangs ingfo gan

**Comment by Nurutomo** [comment]
fixed  :v
