### ISSUE TITLE
Error: spawn convert ENOENT     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)     at onErrorNT (internal/child_process.js:465:16)     at processTicksAndRejections (internal/process/task_queues.js:80:21) {   errno: -2,   code: 'ENOENT',   syscall: 'spawn convert',   path: 'convert',   spawnargs: [ 'webp:-', 'png:-' ] }

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#167]
Eror  Fix Replay Toimg!!

**Comment by Nurutomo** [comment]
pkg install imagemagick
