### ISSUE TITLE
Error: spawn convert ENOENT     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)     at onErrorNT (internal/child_process.js:465:16)     at processTicksAndRejections (internal/process/task_queues.js:80:21) {   errno: -2,   code: 'ENOENT',   syscall: 'spawn convert',   path: 'convert',   spawnargs: [ 'webp:-', 'png:-' ] }

### ISSUE THREAD

**Issue by Bintangp02** [Nurutomo/wabot-aq#193]
Toimg eror!! [Nurutomo](https://github.com/Bintangp02/wabot-aq/issues/new?assignees=&labels=&template=bug_report.md&title=)

**Comment by janganlahkau** [comment]
Pake api ae klo error

**Comment by BochilGaming** [comment]
#148 itu cara fixnya

**Comment by clawbot-navetacandra** [comment]
> Pake api ae klo error

pake api ada limitnya 🙃

**Comment by ai-man-123** [comment]
Ouh

Pada 21 Apr 2021 11:44 AM, "clawbot-navetacandra" ***@***.***>
menulis:

**Comment by Nurutomo** [comment]
toimg butuh install imagemagick :v
