### ISSUE TITLE
Gunanya add, del, get msg itu apa ya? 

### ISSUE THREAD

**Issue by jauhari21** [Nurutomo/wabot-aq#209]
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WAConnection.handler (/data/data/com.termux/files/home/wabot-aq/plugins/listmsg.js:5:10)
    at WAConnection.handler (/data/data/com.termux/files/home/wabot-aq/handler.js:181:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Eror semua commandnya soalnya, apa guanya ga tau cara pakenya ya.

**Comment by RC047** [comment]
Kek save teks, gmbr, video kedatabse bot,, klo mau nambahin add klo mau dapetin get klo hapus del

**Comment by Nurutomo** [comment]
kalo nampilin semua list
