### ISSUE TITLE
speed.js error model property undefined

### ISSUE THREAD

**Issue by anshuljai** [Nurutomo/wabot-aq#287]
here is the error @Nurutomo 

TypeError: Cannot read property 'model' of undefined
    at WAConnection.handler (/data/data/com.termux/files/home/wabot-aq/plugins/speed.js:67:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WAConnection.handler (/data/data/com.termux/files/home/wabot-aq/handler.js:202:13)

**Comment by Nurutomo** [comment]
```os.cpus()``` returns empty array
