### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by riznih** [Nurutomo/wabot-aq#29]
bang kok pas saya deploy di heroku ngak bisa ya?

**Comment by ZefianAlfian** [comment]
> bang kok pas saya deploy di heroku ngak bisa ya?

gabisa gimana? kalo ada errornya coba kirim mungkin bisa bantu

**Comment by ariffb25** [comment]
cara pasang buildpack nya gmn ya?

**Comment by ariffb25** [comment]
![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)

ngga bisa di scan :(

**Comment by ZefianAlfian** [comment]
> ![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)
> 
> ngga bisa di scan :(

scan dj termux dulu kalo udah dapet session nya baru deploy, aku sih gitu

**Comment by ZefianAlfian** [comment]
> cara pasang buildpack nya gmn ya?

ke project heroku terus ke setting , geser ke bawah , cari add buildpack tempel ini 

https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git

tunggu beberapa menit nanti ada deh buildpack nya

**Comment by ariffb25** [comment]
> > ![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)
> > ngga bisa di scan :(
> 
> scan dj termux dulu kalo udah dapet session nya baru deploy, aku sih gitu

sebelumnya udh deploy bareng sessionnya, pas masuk ke Console 'npm start' trs minta scan lagi, yang buildpack udah fix

**Comment by ZefianAlfian** [comment]
> > > ![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)
> > > ngga bisa di scan :(
> > 
> > 
> > scan dj termux dulu kalo udah dapet session nya baru deploy, aku sih gitu
> 
> sebelumnya udh deploy bareng sessionnya, pas masuk ke Console 'npm start' trs minta scan lagi, yang buildpack udah fix

ngapain masuk ke console? bukannya pas di deploy udah langsung jalan otomatis? cek aja di logsnya

**Comment by ariffb25** [comment]
> > > > ![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)
> > > > ngga bisa di scan :(
> > > 
> > > 
> > > scan dj termux dulu kalo udah dapet session nya baru deploy, aku sih gitu
> > 
> > 
> > sebelumnya udh deploy bareng sessionnya, pas masuk ke Console 'npm start' trs minta scan lagi, yang buildpack udah fix
> 
> ngapain masuk ke console? bukannya pas di deploy udah langsung jalan otomatis? cek aja di logsnya

oiya bener, tapi sebentar lgsung mati
```
2021-01-31T05:19:53.084150+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2021-01-31T05:19:53.100724+00:00 heroku[web.1]: Stopping process with SIGKILL
2021-01-31T05:19:53.165427+00:00 heroku[web.1]: Process exited with status 137
2021-01-31T05:19:53.206029+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by ZefianAlfian** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)
> > > > > ngga bisa di scan :(
> > > > 
> > > > 
> > > > scan dj termux dulu kalo udah dapet session nya baru deploy, aku sih gitu
> > > 
> > > 
> > > sebelumnya udh deploy bareng sessionnya, pas masuk ke Console 'npm start' trs minta scan lagi, yang buildpack udah fix
> > 
> > 
> > ngapain masuk ke console? bukannya pas di deploy udah langsung jalan otomatis? cek aja di logsnya
> 
> oiya bener, tapi sebentar lgsung mati
> 
> ```
> 2021-01-31T05:19:53.084150+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
> 2021-01-31T05:19:53.100724+00:00 heroku[web.1]: Stopping process with SIGKILL
> 2021-01-31T05:19:53.165427+00:00 heroku[web.1]: Process exited with status 137
> 2021-01-31T05:19:53.206029+00:00 heroku[web.1]: State changed from starting to crashed
> ```

buka file Procfile ubah jadi

```worker: node index.js```

terus di cmd / termux bekas deploy nya jalan kan command

```heroku scale worker=1```

```heroku ps:restart worker.1```

**Comment by ariffb25** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/76026450/106373311-df7c7d80-63aa-11eb-832b-5b63b251f253.png)
> > > > > > ngga bisa di scan :(
> > > > > 
> > > > > 
> > > > > scan dj termux dulu kalo udah dapet session nya baru deploy, aku sih gitu
> > > > 
> > > > 
> > > > sebelumnya udh deploy bareng sessionnya, pas masuk ke Console 'npm start' trs minta scan lagi, yang buildpack udah fix
> > > 
> > > 
> > > ngapain masuk ke console? bukannya pas di deploy udah langsung jalan otomatis? cek aja di logsnya
> > 
> > 
> > oiya bener, tapi sebentar lgsung mati
> > ```
> > 2021-01-31T05:19:53.084150+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
> > 2021-01-31T05:19:53.100724+00:00 heroku[web.1]: Stopping process with SIGKILL
> > 2021-01-31T05:19:53.165427+00:00 heroku[web.1]: Process exited with status 137
> > 2021-01-31T05:19:53.206029+00:00 heroku[web.1]: State changed from starting to crashed
> > ```
> 
> buka file Procfile ubah jadi
> 
> `worker: node index.js`
> 
> terus di cmd / termux bekas deploy nya jalan kan command
> 
> `heroku scale worker=1`
> 
> `heroku ps:restart worker.1`

nice...👍 tapi perintah pas masukin perintah stiker begini
```
2021-01-31 05:43:52.168 +0000] (16): Saving database . . .
2021-01-31T05:43:52.169461+00:00 app[web.1]:     class: "Baileys"
2021-01-31T05:43:52.170725+00:00 app[web.1]: INFO	 [2021-01-31 05:43:52.170 +0000] (16): Done saving database!
2021-01-31T05:43:52.170726+00:00 app[web.1]:     class: "Baileys"
2021-01-31T05:43:52.417669+00:00 app[web.1]: 6285157336614 ~AstroBot 05:43:51 GMT+0000 (Coordinated Universal Time) 
2021-01-31T05:43:52.417671+00:00 app[web.1]: 6285157336614 ~AstroBot 0|595 to 6285157336614@s.whatsapp.net ~AstroBot extendedText
2021-01-31T05:43:52.417919+00:00 app[web.1]: BaileysError: Decryption failed, HMAC sign does not match
2021-01-31T05:43:52.417921+00:00 app[web.1]:     at Object.decodeMediaMessageBuffer (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:383:11)
2021-01-31T05:43:52.417921+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2021-01-31T05:43:52.417922+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-31T05:43:52.417923+00:00 app[web.1]:     at async WAConnection.downloadMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:298:26)
2021-01-31T05:43:52.417923+00:00 app[web.1]:     at async /app/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
2021-01-31T05:43:52.417924+00:00 app[web.1]:     at async WAConnection.downloadM (/app/lib/simple.js:164:12)
2021-01-31T05:43:52.417924+00:00 app[web.1]:     at async handler (/app/plugins/sticker.js:13:17)
2021-01-31T05:43:52.417925+00:00 app[web.1]:     at async WAConnection.conn.handler (/app/main.js:183:11) {
2021-01-31T05:43:52.417926+00:00 app[web.1]:   status: 400,
2021-01-31T05:43:52.417926+00:00 app[web.1]:   context: { status: 400 }
2021-01-31T05:43:52.417926+00:00 app[web.1]: }
2021-01-31T05:43:52.417972+00:00 app[web.1]: 
2021-01-31T05:43:52.430757+00:00 app[web.1]: decryption of imageMessage media with original HKDF key failed
2021-01-31T05:43:52.437886+00:00 app[web.1]: (node:16) UnhandledPromiseRejectionWarning: BaileysError: Decryption failed, HMAC sign does not match
2021-01-31T05:43:52.437887+00:00 app[web.1]:     at Object.decodeMediaMessageBuffer (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:383:11)
2021-01-31T05:43:52.437888+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2021-01-31T05:43:52.437889+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-31T05:43:52.437891+00:00 app[web.1]:     at async WAConnection.downloadMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:298:26)
2021-01-31T05:43:52.437892+00:00 app[web.1]:     at async /app/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
2021-01-31T05:43:52.437892+00:00 app[web.1]:     at async WAConnection.downloadM (/app/lib/simple.js:164:12)
2021-01-31T05:43:52.438508+00:00 app[web.1]: (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see 
```
ngga lengkap copy nya, pokoknya ada teks **ngga bisa unlink gitu**

**Comment by ZefianAlfian** [comment]
> > buka file Procfile ubah jadi
> > `worker: node index.js`
> > terus di cmd / termux bekas deploy nya jalan kan command
> > `heroku scale worker=1`
> > `heroku ps:restart worker.1`
> 
> nice...👍 tapi perintah pas masukin perintah stiker begini
> 
> ```
> 2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
> 2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
> 2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
> 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
> 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
> 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
> 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
> 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
> 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
> 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
> 2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
> ```
> 
> ngga lengkap copy nya, pokoknya ada teks **ngga bisa unlink gitu**

wah gatau deh yang bikin script bukan aku, @Nurutomo

**Comment by ariffb25** [comment]
> > > buka file Procfile ubah jadi
> > > `worker: node index.js`
> > > terus di cmd / termux bekas deploy nya jalan kan command
> > > `heroku scale worker=1`
> > > `heroku ps:restart worker.1`
> > 
> > 
> > nice...👍 tapi perintah pas masukin perintah stiker begini
> > ```
> > 2021-01-31T06:25:01.024909+00:00 app[worker.1]: Error: ENOENT: no such file or directory, unlink '/app/tmp/1612074300852.png'
> > 2021-01-31T06:25:01.024917+00:00 app[worker.1]:     at Object.unlinkSync (fs.js:1136:3)
> > 2021-01-31T06:25:01.024918+00:00 app[worker.1]:     at ChildProcess.<anonymous> (/app/plugins/sticker.js:64:18)
> > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at ChildProcess.emit (events.js:314:20)
> > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at maybeClose (internal/child_process.js:1022:16)
> > 2021-01-31T06:25:01.024919+00:00 app[worker.1]:     at Socket.<anonymous> (internal/child_process.js:444:11)
> > 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Socket.emit (events.js:314:20)
> > 2021-01-31T06:25:01.024920+00:00 app[worker.1]:     at Pipe.<anonymous> (net.js:675:12) {
> > 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   errno: -2,
> > 2021-01-31T06:25:01.024921+00:00 app[worker.1]:   syscall: 'unlink',
> > 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   code: 'ENOENT',
> > 2021-01-31T06:25:01.024922+00:00 app[worker.1]:   path: '/app/tmp/1612074300852.png'
> > 2021-01-31T06:25:01.024923+00:00 app[worker.1]: } uncaughtException
> > ```
> > 
> > 
> > ngga lengkap copy nya, pokoknya ada teks **ngga bisa unlink gitu**
> 
> wah gatau deh yang bikin script bukan aku, @Nurutomo

pas nyoba imagemagick nya di install pertama baru bisa tapi hasil nya

![IMG_20210201_070841](https://user-images.githubusercontent.com/76026450/106402524-70f7f800-645c-11eb-82a5-2c792cfbd69b.jpg)

**Comment by rizalkun321** [comment]
kok gw error kek gini TypeError: Object.fromEntries is not a function

**Comment by ZefianAlfian** [comment]
> kok gw error kek gini TypeError: Object.fromEntries is not a function

gatau, gapernah dapet error gitu

**Comment by ariffb25** [comment]
selain heroku bisa dideploy dimana?

**Comment by Nurutomo** [comment]
Dyno `node index.js --server`

QR nya nanti bisa diakses di web
