### ISSUE TITLE
caripesan.js TypeError

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#316]
TypeError: Cannot read property 'toString' of undefined
    at WAConnection.searchMessages (C:\Users\Administrator\Documents\GitHub\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\7.MessagesExtra.js:256:30)
    at WAConnection.handler (C:\Users\Administrator\Documents\GitHub\wabot-aq\plugins\caripesan.js:4:29)
    at WAConnection.handler (C:\Users\Administrator\Documents\GitHub\wabot-aq\handler.js:236:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Nurutomo** [comment]
Itu error dari baileys nya, bukan bot
