### ISSUE TITLE
jadibot Error: intentional

### ISSUE THREAD

**Issue by Ftwrr** [Nurutomo/wabot-aq#329]
WARN [2021-05-31 12:38:14.534 +0000] (3492): connect attempt 1 failed: Error: intentional
    class: "Baileys"
    error: {}
Error: intentional
    at WAConnection.rejectAllOnWSClose (C:\Users\Administrator\Documents\GitHub\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:79:62)
    at WAConnection.emit (node:events:377:35)
    at WAConnection.emit (C:\Users\Administrator\Documents\GitHub\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41)
    at WAConnection.endConnection (C:\Users\Administrator\Documents\GitHub\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:415:14)
    at WAConnection.closeInternal (C:\Users\Administrator\Documents\GitHub\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:398:14)
    at WAConnection.close (C:\Users\Administrator\Documents\GitHub\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:390:14)
    at Timeout._onTimeout (C:\Users\Administrator\Documents\GitHub\wabot-aq\plugins\jadibot.js:42:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) unhandledRejection

**Comment by Nurutomo** [comment]
its intentional because there is `conn.close()` after timeout 60 seconds

**Comment by Ftwrr** [comment]
> its intentional because there is `conn.close()` after timeout 60 seconds

lalu aku harus apa :(
