### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/app/tmp/1622604011370.jpeg.png.webp' - heroku

### ISSUE THREAD

**Issue by QUERY-GANI** [Nurutomo/wabot-aq#342]
**Describe the bug**
Saya sedang mencoba menggunakan command sticker tetapi itu tidak bekerja jika saya run botnya di heroku

**To Reproduce**
1. Error di terminal:
```bash
2021-06-02T03:20:11.859216+00:00 app[worker.1]: Error: ENOENT: no such file or directory, open '/app/tmp/1622604011370.jpeg.png.webp'
2021-06-02T03:20:11.859233+00:00 app[worker.1]: at Object.openSync (fs.js:498:3)
2021-06-02T03:20:11.859233+00:00 app[worker.1]: at Object.readFileSync (fs.js:394:35)
2021-06-02T03:20:11.859234+00:00 app[worker.1]: at ChildProcess.<anonymous> (/app/lib/sticker.js:40:22)
2021-06-02T03:20:11.859234+00:00 app[worker.1]: at ChildProcess.emit (events.js:376:20)
2021-06-02T03:20:11.859234+00:00 app[worker.1]: at maybeClose (internal/child_process.js:1055:16)
2021-06-02T03:20:11.859235+00:00 app[worker.1]: at Socket.<anonymous> (internal/child_process.js:441:11)
2021-06-02T03:20:11.859235+00:00 app[worker.1]: at Socket.emit (events.js:376:20)
2021-06-02T03:20:11.859235+00:00 app[worker.1]: at Pipe.<anonymous> (net.js:673:12) {
2021-06-02T03:20:11.859236+00:00 app[worker.1]: errno: -2,
2021-06-02T03:20:11.859237+00:00 app[worker.1]: syscall: 'open',
2021-06-02T03:20:11.859237+00:00 app[worker.1]: code: 'ENOENT',
2021-06-02T03:20:11.859237+00:00 app[worker.1]: path: '/app/tmp/1622604011370.jpeg.png.webp'
2021-06-02T03:20:11.859238+00:00 app[worker.1]: } uncaughtException
```

**Expected behavior**
Saya ingin command sticker work jika di jalankan di heroku

**Screenshots**
* folder di root project
![image](https://user-images.githubusercontent.com/73988956/120419428-a53ce000-c38c-11eb-8925-66e39606f0bd.png)

* Isi dari tmp folder
![image](https://user-images.githubusercontent.com/73988956/120419456-b38afc00-c38c-11eb-8e59-8f72c4f05110.png)

* My buildpack
![image](https://user-images.githubusercontent.com/73988956/120422016-99075180-c391-11eb-8d87-4fd1e2c99156.png)

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 88.0.1

**Smartphone (please complete the following information):**
 - Device: Oppo
 - OS: ColorOS
 - Version 2.1.0i

**Additional context**
sticker bekerja dengan baik jika saya run di local

**Comment by QUERY-GANI** [comment]
work setelah update :)
