### ISSUE TITLE
Error command !pay & !paylimit 

### ISSUE THREAD

**Issue by xaryow** [Nurutomo/wabot-aq#346]
TypeError: Cannot read property 'exp' of undefined
    at WAConnection.handler (C:\Users\admin\Desktop\wabot-aq\plugins\pay.js:19:8)
    at WAConnection.handler (C:\Users\admin\Desktop\wabot-aq\handler.js:245:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

TypeError: Cannot read property 'limit' of undefined
    at WAConnection.handler (C:\Users\admin\Desktop\wabot-aq\plugins\paylimit.js:19:10)
    at WAConnection.handler (C:\Users\admin\Desktop\wabot-aq\handler.js:245:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by ariffb25** [comment]
itu karena user tidak ada di database.json
