### ISSUE TITLE
handker is not defined

### ISSUE THREAD

**Issue by Rianfirnanda** [Nurutomo/wabot-aq#356]
ERROR [2021-06-04 02:50:07.606 +0000] (12468): handker is not defined
    ReferenceError: handker is not defined
        at Object.<anonymous> (C:\Users\users\wabot-aq\plugins\odemote.js:11:1)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (C:\Users\users\wabot-aq\main.js:157:32)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by Rianfirnanda** [comment]
wabot-aq\plugins\odemote.js:11:1
handler.owner = true

**Comment by Ftwrr** [comment]
itu typo
handler

**Comment by Rianfirnanda** [comment]
> itu typo
> handler

Yoi udah gw gnti

**Comment by FadliDarmawan** [comment]
> ERROR [2021-06-04 02:50:07.606 +0000] (12468): handker is not defined
>     ReferenceError: handker is not defined
>         at Object.<anonymous> (C:\Users\users\wabot-aq\plugins\odemote.js:11:1)
>         at Module._compile (internal/modules/cjs/loader.js:1063:30)
>         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>         at Module.load (internal/modules/cjs/loader.js:928:32)
>         at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>         at Module.require (internal/modules/cjs/loader.js:952:19)
>         at require (internal/modules/cjs/helpers.js:88:18)
>         at Object.<anonymous> (C:\Users\users\wabot-aq\main.js:157:32)
>         at Module._compile (internal/modules/cjs/loader.js:1063:30)
>         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

Handler bro
