### ISSUE TITLE
Bantu

### ISSUE THREAD

**Issue by Lord-Gaming** [Nurutomo/wabot-aq#450]
Pas gw coba running text keluar kek gini

TypeError: m.download is not a function
    at WAConnection.handler (C:\wabot-aq\plugins\runningtext.js:4:21)
    at WAConnection.handler (C:\wabot-aq\handler.js:246:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Knp tu?

**Comment by ariffb25** [comment]
coba sambil reply/balas gambar

**Comment by Lord-Gaming** [comment]
yg jalan gambar yg di reply :v

**Comment by Nurutomo** [comment]
itu sebenarnya fitur buat attp2, tpi gabisa transparan...jadilah gitu :v
