### ISSUE TITLE
Semoji Error

### ISSUE THREAD

**Issue by Lord-Gaming** [Nurutomo/wabot-aq#456]
Pas gw ketik #semoji whatsapp 🗿 malah kek gini

TypeError: Cannot use 'in' operator to search for 'whatsapp' in https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/whatsapp/273/moai_1f5ff.png
    at WAConnection.handler (c:\wabot-aq\plugins\semoji.js:27:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WAConnection.handler (c:\wabot-aq\handler.js:246:13)

Knp tu?

**Comment by Nurutomo** [comment]
hmm

**Comment by Nurutomo** [comment]
fixed
