### ISSUE TITLE
fix textpro

### ISSUE THREAD

**Issue by Wahyudianshar** [Nurutomo/wabot-aq#493]
Tolong bang nuru fix fitur textpro dong soalnya banyak yg eror :(

makasih hehe

**Comment by Users1233** [comment]
yang mana aja?

**Comment by Nurutomo** [comment]
coba dicek dulu, itu butuh 2 teks apa nggk

**Comment by Wahyudianshar** [comment]
Error: marker was not found
    at decodeScan (/data/data/com.termux/files/home/wabot-aq/node_modules/jpeg-js/lib/decoder.js:344:15)
    at constructor.parse (/data/data/com.termux/files/home/wabot-aq/node_modules/jpeg-js/lib/decoder.js:804:29)
    at Object.decode [as image/jpeg] (/data/data/com.termux/files/home/wabot-aq/node_modules/jpeg-js/lib/decoder.js:1096:11)
    at Jimp.parseBitmap (/data/data/com.termux/files/home/wabot-aq/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/data/data/com.termux/files/home/wabot-aq/node_modules/@jimp/core/dist/index.js:431:32)
    at /data/data/com.termux/files/home/wabot-aq/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}

**Comment by Wahyudianshar** [comment]
Kayak gitu bang :(
