### ISSUE TITLE
TTS Command Error 

### ISSUE THREAD

**Issue by 0x0n1** [Nurutomo/wabot-aq#580]
```
ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
    class: "Baileys"
ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
    class: "Baileys"
(node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
    at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
    at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
    at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
    at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TOXIC-DEVIL** [comment]
> ```
> ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
>     class: "Baileys"
> ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
>     class: "Baileys"
> (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
>     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
>     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
>     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
>     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

You used, Deployed on heroku or not?

**Comment by Bintangp02** [comment]
> > ```
> > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> >     class: "Baileys"
> > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> >     class: "Baileys"
> > (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
> >     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> >     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
> >     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
> >     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
> >     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ```
> 
> You used, Deployed on heroku or not?

*I haven't tried using heroku yet..*
*Saya belum mengunakan heroku (semoga gak eror*

**Comment by TOXIC-DEVIL** [comment]
> > > ```
> > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > >     class: "Baileys"
> > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > >     class: "Baileys"
> > > (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
> > >     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
> > >     at runMicrotasks (<anonymous>)
> > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > >     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
> > >     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
> > >     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
> > >     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> > > (Use `node --trace-warnings ...` to show where the warning was created)
> > > (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > > (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > ```
> > 
> > 
> > You used, Deployed on heroku or not?
> 
> _I haven't tried using heroku yet.._
> _Saya belum mengunakan heroku (semoga gak eror_

Okay!! *I have a request 😂*, Can You Please **Follow Me** 😂

**Comment by Bintangp02** [comment]
> > > > ```
> > > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > > >     class: "Baileys"
> > > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > > >     class: "Baileys"
> > > > (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
> > > >     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
> > > >     at runMicrotasks (<anonymous>)
> > > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > > >     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
> > > >     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
> > > >     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
> > > >     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> > > > (Use `node --trace-warnings ...` to show where the warning was created)
> > > > (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > > > (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > > ```
> > > 
> > > 
> > > You used, Deployed on heroku or not?
> > 
> > 
> > _I haven't tried using heroku yet.._
> > _Saya belum mengunakan heroku (semoga gak eror_
> 
> Okay!! _I have a request 😂_, Can You Please **Follow Me** 😂


>>>>>>>>>> Jagan Lupa Follow back🤣
Yes ,,Jagan lupa folow back 🤣🤔

**Comment by TOXIC-DEVIL** [comment]
> > > > > ```
> > > > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > > > >     class: "Baileys"
> > > > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > > > >     class: "Baileys"
> > > > > (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
> > > > >     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
> > > > >     at runMicrotasks (<anonymous>)
> > > > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > > > >     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
> > > > >     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
> > > > >     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
> > > > >     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> > > > > (Use `node --trace-warnings ...` to show where the warning was created)
> > > > > (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > > > > (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > > > ```
> > > > 
> > > > 
> > > > You used, Deployed on heroku or not?
> > > 
> > > 
> > > _I have not tried using Heroku yet .. _
> > > _I do not use Heroku (hopefully not an error_
> > 
> > 
> > Okay!! _I have a request 😂_, Can You Please **Follow Me** 😂
> 
> > > > > > > > > Jagan Lupa Follow back🤣
> 
> Yes, I forgot to follow back 🤣🤔

😂👋

**Comment by 0x0n1** [comment]
> > ```
> > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> >     class: "Baileys"
> > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> >     class: "Baileys"
> > (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
> >     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> >     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
> >     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
> >     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
> >     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ```
> 
> You used, Deployed on heroku or not?

no bro, im using a windows vps to deploy this bot.

**Comment by TOXIC-DEVIL** [comment]
> > > ```
> > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > >     class: "Baileys"
> > > ERROR [2021-07-15 04:10:39.058 +0000] (6248): Error in uploading to mmh.whatsapp.net (RequestError: getaddrinfo ENOTFOUND mmh.whatsapp.net)
> > >     class: "Baileys"
> > > (node:6248) UnhandledPromiseRejectionWarning: Error: Media upload failed on all hosts
> > >     at WAConnection.prepareMessageMedia (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:209:19)
> > >     at runMicrotasks (<anonymous>)
> > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > >     at async WAConnection.prepareMessageContent (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:21)
> > >     at async WAConnection.prepareMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:25)
> > >     at async WAConnection.sendMessage (C:\wabot-aq\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:24:27)
> > >     at async WAConnection.sendFile (C:\wabot-aq\lib\simple.js:249:14)
> > > (Use `node --trace-warnings ...` to show where the warning was created)
> > > (node:6248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > > (node:6248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > ```
> > 
> > 
> > You used, Deployed on heroku or not?
> 
> no bro, im using a windows vps to deploy this bot.

Oh 😁
