### ISSUE TITLE
#textpro errror

### ISSUE THREAD

**Issue by aryaxplofc** [Nurutomo/wabot-aq#708]
Mau nanya om gua pas gunain command #textpro ko error' yah kek gini, btw gua udh premium xteam

Error: marker was not found
    at decodeScan (/data/data/com.termux/files/home/wabot-aq/node_modules/jpeg-js/lib/decoder.js:344:15)
    at constructor.parse (/data/data/com.termux/files/home/wabot-aq/node_modules/jpeg-js/lib/decoder.js:804:29)
    at Object.decode [as image/jpeg] (/data/data/com.termux/files/home/wabot-aq/node_modules/jpeg-js/lib/decoder.js:1096:11)
    at Jimp.parseBitmap (/data/data/com.termux/files/home/wabot-aq/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/data/data/com.termux/files/home/wabot-aq/node_modules/@jimp/core/dist/index.js:431:32)
    at /data/data/com.termux/files/home/wabot-aq/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}

**Comment by Ftwrr** [comment]
```thumbnail: Buffer.alloc(0)```
mungkin

**Comment by ariffb25** [comment]
> `thumbnail: Buffer.alloc(0)`
> mungkin

tambahan

```js
  await conn.sendFile(m.chat, url, 'file.jpg', `*TEXTPRO*\n*Efek:* ${effect}`, m, 0, { thumbnail: await(await fetch(url)).buffer() })
```
