### ISSUE TITLE
Brainly Error

### ISSUE THREAD

**Issue by navetacandra24** [Nurutomo/wabot-aq#97]
Brainly-nya kok suka error sih, kira kira kenapa bang?

```Javascript
   Error: Request failed with status code 403
    at createError (/workspace/main-server/bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/workspace/main-server/bot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/workspace/main-server/bot/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  config: {
    url: 'https://brainly.co.id/graphql/id',
    method: 'post',
    data: '{"operationName":"SearchQuery","variables":{"query":"tes","after":null,"first":5},"query":"query SearchQuery($query: String!, $first: Int!, $after: ID) {\\n
\\tquestionSearch(query: $query, first: $first, after: $after) {\\n\\tedges {\\n\\t  node {\\ncontent\\n\\t\\tattachments{\\nurl\\n}\\n\\t\\tanswers {\\n\\t\\t\\tnodes
 {\\ncontent\\n\\t\\t\\t\\tattachments{\\nurl\\n}\\n}\\n}\\n}\\n}\\n}\\n}\\n"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json; charset=utf-8',
      host: 'brainly.co.id',
      'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.27 (KHTML, like Gecko) Chrome/12.0.712.0 Safari/534.27',
      'Content-Length': 367
    },
    ....
```

**Comment by Nurutomo** [comment]
Dari server brainly nya atau modukenya

**Comment by navetacandra24** [comment]
> Dari server brainly nya atau modulenya

Solusi?
